/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sphbookrecords;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Perks
 */
public class dataEntry extends javax.swing.JFrame {

    /**
     * Creates new form dataEntry
     */
    public dataEntry() {
        initComponents();
        displayTable();
    }
    
    public void displayTable(){
        updateTable();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sphbookinventory","root","");
            
            Statement st = con.createStatement();
            String sql = "select * from bookroster";
            ResultSet rs = st.executeQuery(sql);
            System.out.println("Hi");
            while(rs.next()){
                String ID = String.valueOf(rs.getInt("ID"));
                String Title = String.valueOf(rs.getString("title"));
                String Author = String.valueOf(rs.getString("author"));
                String Quantity = String.valueOf(rs.getString("quantity"));
                
                String tbData[] = {ID, Title,Author,Quantity};
                  DefaultTableModel tblModel = (DefaultTableModel)ContainerTable.getModel();
                  tblModel.addRow(tbData);
                
            }
            con.close();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }
    
     private void updateTable(){
          DefaultTableModel tblModel = (DefaultTableModel)ContainerTable.getModel();
          tblModel.setRowCount(0);
          ContainerTable.revalidate();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContainerTable = new javax.swing.JTable();
        enterTitle = new javax.swing.JTextField();
        enterAuthor = new javax.swing.JTextField();
        nameTitle = new javax.swing.JLabel();
        nameAuthor = new javax.swing.JLabel();
        bookAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entry");

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        ContainerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ContainerTable);
        if (ContainerTable.getColumnModel().getColumnCount() > 0) {
            ContainerTable.getColumnModel().getColumn(0).setResizable(false);
            ContainerTable.getColumnModel().getColumn(1).setResizable(false);
            ContainerTable.getColumnModel().getColumn(2).setResizable(false);
            ContainerTable.getColumnModel().getColumn(3).setResizable(false);
        }

        enterTitle.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        enterTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTitleActionPerformed(evt);
            }
        });

        enterAuthor.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        enterAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterAuthorActionPerformed(evt);
            }
        });

        nameTitle.setBackground(new java.awt.Color(0, 51, 204));
        nameTitle.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        nameTitle.setForeground(new java.awt.Color(255, 255, 255));
        nameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameTitle.setText("Title");

        nameAuthor.setBackground(new java.awt.Color(0, 51, 204));
        nameAuthor.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        nameAuthor.setForeground(new java.awt.Color(255, 255, 255));
        nameAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameAuthor.setText("Author");

        bookAdd.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        bookAdd.setText("Add Book");
        bookAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        entryButtons.add(bookAdd);
        bookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Addington CF Regular", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Details:");

        mainMenu.setFont(new java.awt.Font("Addington CF Regular", 0, 18)); // NOI18N
        mainMenu.setText("Main Menu");
        mainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        entryButtons.add(mainMenu);
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterTitle)
                            .addComponent(enterAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(enterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(enterAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(bookAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTitleActionPerformed

    private void enterAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterAuthorActionPerformed

    private void bookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAddActionPerformed
        String bkTitle = enterTitle.getText();
        String bkAuthor = enterAuthor.getText();
        int bookQuantity = +1;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/sphbookinventory","root","");
            String query = "INSERT INTO bookroster (`title`, `author`, `quantity`) VALUES (?, ?, ?)";
            PreparedStatement insert = con1.prepareStatement(query);
            insert.setString(1, bkTitle);
            insert.setString(2, bkAuthor);
            insert.setInt(3, bookQuantity);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Saved");
            enterTitle.setText("");
            enterAuthor.setText("");
            enterTitle.requestFocus();
            displayTable();
        } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(dataEntry.class.getName()).log(Level.SEVERE, null, ex);
        } JOptionPane.showMessageDialog(this, "Book Added to Library!");
    }//GEN-LAST:event_bookAddActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        mainMenu maNu = new mainMenu();
        maNu.displayform();
        this.dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataEntry().setVisible(true);
            }
        });
    }

    public void displayform() {
        setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContainerTable;
    private javax.swing.JButton bookAdd;
    private javax.swing.JTextField enterAuthor;
    private javax.swing.JTextField enterTitle;
    private javax.swing.ButtonGroup entryButtons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu;
    private javax.swing.JLabel nameAuthor;
    private javax.swing.JLabel nameTitle;
    // End of variables declaration//GEN-END:variables
}
